### PR TITLE
Design level IC5 = Staff

### PR DESCRIPTION
**Pull request by rrhyne**
Changes the description on IC5 from "Expert" to "Staff"

### CODE REVIEW

**Review by ErikaRS — COMMENTED** [review]
It looks like you picked up some sketchy changes content/company-info-and-process/about-sourcegraph/general-office-info.md (I think there was someone trying to spam our accounts earlier). Can you revert this file?

**Comment by rrhyne** [comment]
It's prettier, so I'm not convinced I or someone else wouldn't pick up the same change. Might as well have the file linted correctly?

**Comment by ErikaRS** [comment]
Fair!

**Comment by ErikaRS** [comment]
LGTM then 😄

**Review by toolmantim — APPROVED** [review]

**Pull request merged**
