### PR TITLE
Update Cloud teams info

### PR DESCRIPTION
**Pull request by anna-mmikhova**
Update cloud teams info (where available)

### CODE REVIEW

**Review by malomarrec — APPROVED** [review]

**Comment by jasonyavorsky** [comment]
@anna-mmikhova this was failing because the extensions team was renamed, but there were still features that were pointed at the now missing extensions team. I updated them to point to the growth & integrations team, is that right?

**Comment by jasonyavorsky** [comment]
It was also failing because Murat's name was misspelled

**Comment by jasonyavorsky** [comment]
One more question @anna-mmikhova - the delivery team was deleted, but there's still a page in the handbook at strategy_link: /company/strategy/enablement/delivery/index.md. Is that intentional?

**Comment by anna-mmikhova** [comment]
I left the delivery link under DevOps for now while we restructure the Cloud org pages, it's quite a mess

**Pull request merged**
