### PR TITLE
Embed slide decks for cross-functional projects

### PR DESCRIPTION
**Pull request by felixfbecker**
I loved the presentations for the cross-functional projects at Sourcegraph Merge. I think they gave a great overview and were able to do that much better to a department-wide audience than all the prior docs and messaging (not saying those are not good, I just think this works really well for the wider audience).

Since we only get the opportunity to get together and hold a department-wide presentation twice a year, I've been thinking about how we can maintain the benefits of that medium even in between offsites. I think we should use Slide decks more in general as a medium within the handbook.

So this PR embeds the slide decks for the Strategic Readiness CP and the Code Intelligence Platform CP as overviews on their respective CP pages. All the other content is still there of course, but anyone who would appreciate a visual overview can immediately click through the slide deck or watch it in full screen. This can also serve as an example for future projects or other topics.

The content will **only be visible to Sourcegraph teammates signed into Google**, so there is no worry about any private data in those slide decks leaking.

@malomarrec the presentation for product-led didn't have a CP page for it – we only have an existing bizops page on this, but there already is another slide deck linked from it, so this engineering-focused presentation didn't fit well there. I therefore didn't add that slide deck anywhere so far.

### CODE REVIEW

**Review by Joelkw — APPROVED** [review]
This is dope! Strong approve.

**Comment by Joelkw** [comment]
Now I'm thinking about stealing this for pages like this https://handbook.sourcegraph.com/departments/engineering/teams/code-insights/go_to_market/#code-insights-go-to-market-resources ...

**Comment by felixfbecker** [comment]
Do it! 😎 

Slide decks, Zoom recordings (including captions!), Looms, Google Docs, Looker looks, Figma files, Calendly, ... are all possible to be embedded (with proper authentication)!

**Comment by malomarrec** [comment]
Awesome addition @felixfbecker.
Added mine as part of this PR https://github.com/sourcegraph/handbook/pull/4853

**Review by ryphil — APPROVED** [review]
Love it :)

**Pull request merged**
