### PR TITLE
Add roadmap philosophy

### PR DESCRIPTION
**Pull request by malomarrec**
Add some short roadmap principles so that everybody is on the same page for what a roadmap means, and what roamdap we want to produce at sourcegraph and why.

### CODE REVIEW

**Review by sqs — APPROVED** [review]
Perfect

**Review by taylorsperry — APPROVED** [review]

**Review by ryphil — APPROVED** [review]

**Comment by amenne** [comment]
Hey @malomarrec on the GTM side some questions came up during our review:
- Does the 3 month roadmap include experimental and standard improvements to capabilities? What’s the likelihood (percentage-wise) to deliver the items on the 3 month roadmap (eg 90%+)?
- ‘Best effort 6-month+ roadmap for enterprise readiness’, what does this mean specifically: best effort and enterprise readiness?
- What’s the likelihood (percentage-wise) to deliver the items on the 6 month roadmap (eg 50%+)?
- Walk us through the 3 month and 6 month roadmaps, how they relate to each other and how they relate to the high-level 1 year narrative.
- Are there any particular considerations around lead times for decisions and priorities as it relates to engineering resourcing?

Thanks!

**Comment by malomarrec** [comment]
> Does the 3 month roadmap include experimental and standard improvements to capabilities? What’s the likelihood (percentage-wise) to deliver the items on the 3 month roadmap (eg 90%+)?

- Yes. Experiments will be tagged with experimental, which means they have a 50% change of progressing to Beta.
- I think we should have a high bar (90%) for delivering roadmapped things over the next 3 months. 90% sounds good. It'd mean that of 10 PR-FAQs or job fair items, 1 gets cancelled. Sounds reasonable.

> ‘Best effort 6-month+ roadmap for enterprise readiness’, what does this mean specifically: best effort and enterprise readiness?

We aim to have strat-readiness and admin experience thing planned further ahead than features, because they are more predictable. This also aligns with customer expectations: larger customers tend to have more needs for both admin readiness and predictability, so we strive to provide that. This is "best-effort" in that we don't have any capacity planning process beyond one quarter so far, so there won't be firm answers here. The uncertainty will not be on the "what shall we build side", but on the "can we commit resources here" side.

> What’s the likelihood (percentage-wise) to deliver the items on the 6 month roadmap (eg 50%+)?
Walk us through the 3 month and 6 month roadmaps, how they relate to each other and how they relate to the high-level 1 year narrative.

I'll also tag @ryphil here as the main owner of this part.


> Are there any particular considerations around lead times for decisions and priorities as it relates to engineering resourcing?

Defering eng resourcing and planning to @steveyegge

**Comment by malomarrec** [comment]
Added further clarification here @amenne https://github.com/sourcegraph/handbook/pull/6824

**Pull request merged**
