### PR TITLE
add AARRR experiment

### PR DESCRIPTION
**Pull request by rrhyne**
Adds a page to planning experimentations

### CODE REVIEW

**Review by benvenker — APPROVED** [review]
Looks great!

**Review by jasonyavorsky — APPROVED** [review]
Looks good, but rather than adding a page information on what we might do, might it be better to link to a PR to the planning page (https://handbook.sourcegraph.com/product/product_management/planning) that implements these changes?

**Comment by rrhyne** [comment]
> Looks good, but rather than adding a page information on what we might do, might it be better to link to a PR to the planning page (https://handbook.sourcegraph.com/product/product_management/planning) that implements these changes?


@jyavorska I would rather not have an open PR sitting around for a month or two so I added the experimental section to that page. WDYT?

**Comment by jasonyavorsky** [comment]
Oh that's fine @rrhyne I didn't realize there was a couple months left here.

**Pull request merged**
