### PR TITLE
Update Batch Changes positioning page to be more actionable

### PR DESCRIPTION
**Pull request by malomarrec**
We have learnt a lot since launch. We have now narrowed down some repeatable sales and use cases patterns. There are others we are still discovering and testing out (eg. security), but we should focus on what works, while discovering more.

This PR brings those learning to this page. I took the angle of making it more tactical ("what could a sales team mate use effectively"). The strategic positioning source of truth is in the batch changes [strategy page](https://handbook.sourcegraph.com/company/strategy/code-graph/batch-changes) (PRs welcome there).

I also tightened up some of the wording to align with what we use in practice.

### CODE REVIEW

**Comment by malomarrec** [comment]
I didn't tag CE for review, but @sourcegraph/customer-engineering I'd love your review on this page, as well as anything you need to make it more useful.

**Review by abschu — COMMENTED** [review]
@malomarrec - thanks for updating this. Since we're working on defining "use cases" as a company, how would you feel about changing "use case" to "How Batch Changes can help" or "Product use case?"

**Comment by jasonyavorsky** [comment]
Looks good to me @malomarrec, lets include @thisisvic also.

**Review by jasonyavorsky — APPROVED** [review]

**Review by chrispine — APPROVED** [review]

**Comment by malomarrec** [comment]
@thisisvic I merged this, but follow-up PRs are welcome!

**Pull request merged**
