### PR TITLE
Remove quotes around links that lead to mixed-up smart quotes after r…

### PR DESCRIPTION
**Pull request by bostick**
…unning retext

### CODE REVIEW

**Comment by bostick** [comment]
Quotes around links are not supported, e.g.:
https://github.com/retextjs/retext-smartypants/issues/2

**Comment by bostick** [comment]
Screen Shot 2021-12-14 at 5 15 02 PM

**Comment by bostick** [comment]
Screen Shot 2021-12-14 at 5 19 06 PM

**Comment by bostick** [comment]
Screen Shot 2021-12-14 at 5 20 01 PM

**Comment by bostick** [comment]
The opening smart quotes and closing smart quotes are swapped

**Review by jeanduplessis — APPROVED** [review]

**Pull request merged**
