### PR TITLE
Create people ops pm page

### PR DESCRIPTION
**Pull request by marybelzer**

### CODE REVIEW

**Comment by marybelzer** [comment]
@DebbieSG @InesRoitman @cassiemelani @CecilyBlack @mercadon here are the handbook changes i proposed in [RFC 491](https://docs.google.com/document/d/1-4ItdngXZ_OzY5tBysKE3mXaIIWxo1NUJVDIPpuk5ic/edit#). When you all create the Q4 board, we can link it here. Added you all as approvers, you can let me know via PR comment when you're ready to push this live. Or, if you don't want to put this in the Handbook yet, let me know and I will close the PR.

**Review by InesRoitman — APPROVED** [review]
This looks AMAZING! Thank you :)

**Review by CecilyBlack — APPROVED** [review]
I edited the file to include updates to formatting + a change to what qualifies something as a board card.

Thanks so much for creating this!

**Review by cassiemelani — APPROVED** [review]
LGTM :)

**Pull request merged**
