### PR TITLE
Spelling updates

### PR DESCRIPTION
**Pull request by DocAdam**
sensitve - sensitive 
git flow - git-flow
by - with

### CODE REVIEW

**Review by danieldides — APPROVED** [review]

**Review by daxmc99 — CHANGES_REQUESTED** [review]
Do we have a CLA on file for this user @danieldides?

**Review by daxmc99 — APPROVED** [review]
LGTM, confirmed we have a signed CLA for this user.

**Comment by daxmc99** [comment]
@DocAdam Could you consolidate your PRs to a single PR? Most of these are spelling and they could be merged as a single PR more quickly?

**Comment by DocAdam** [comment]
> @DocAdam Could you consolidate your PRs to a single PR? Most of these are spelling and they could be merged as a single PR more quickly?

I don't know how to do that. Can you link me to something that has steps on how to make them a single PR? I am happy to learn, but could use some pointers. @daxmc99

**Comment by daxmc99** [comment]
@DocAdam I'm not entirely sure of your workflow but we do have some [docs](https://handbook.sourcegraph.com/handbook/editing) here. 
You may also find the Github Desktop useful https://desktop.github.com/

Essentially, instead of making each edit online and creating a new branch (in this case, the name of your branch is `patch-108` (which is what I assume your current workflow is) you would contain all your changes to a single branch. 

For an overview of Git branching, I would suggest this [site](https://learngitbranching.js.org/?locale=en_US)

Regardless, we appreciate you doing this! 🎉   and we will continue to review these as we have time

**Comment by DocAdam** [comment]
OK @daxmc99 I combined them all into this one as requested. I hope this works better. And thank you for your patience! I appreciate your assistance in helping me out with the workflow.

**Comment by DocAdam** [comment]
I don't have write access to Merge these changes - @daxmc99 or @danieldides are you able to do this for me? Thanks for your help.

**Pull request closed without merging**
