### PR TITLE
Remove myself from notifications

### PR DESCRIPTION
**Pull request by felixfbecker**
👋🏻

### CODE REVIEW

**Comment by felixfbecker** [comment]
Maybe I can get a review from @vovakulikov ? :)

**Comment by vovakulikov** [comment]
Hehe, I don't know Felix, what do I get for this?

**Review by vovakulikov — APPROVED** [review]
🆓

**Comment by felixfbecker** [comment]
@vovakulikov Could you merge it too? 😅

**Comment by chrispine** [comment]
Haha, sorry we dropped this one, Felix!

**Comment by vovakulikov** [comment]
Hello, I'm sorry I didn't realise that you can't merge this anymore, @felixfbecker I can't merge this one because CI checks are still in pending (I think they stuck, can you rebase the main and push it again)

**Comment by chrispine** [comment]
Fixed in #6432

**Pull request closed without merging**
