### PR TITLE
Adding support rotation

### PR DESCRIPTION
**Pull request by scalabilitysolved**
Initial draft at a lightweight process for handling incoming support and requests for help for Code Exploration.

### CODE REVIEW

**Review by philipp-spiess — APPROVED** [review]
This is awesome stuff! Should we add some clarification around the time commitment of this support rotation? 

I wrote a similar proposal for the integration team before it fell apart (😢) and one thing I wanted to make clear is that the expectation is strictly to be doing the triaging during the usual work hours. 

Here's the page for integration for reference: https://github.com/sourcegraph/handbook/pull/4884/files#diff-7efe0e3a4e015b7d3b0c5913e62c457ef48bc4ce86bca1e04ce05a9d3de17551R11

**Comment by scalabilitysolved** [comment]
> This is awesome stuff! Should we add some clarification around the time commitment of this support rotation?
> 
> I wrote a similar proposal for the integration team before it fell apart (😢) and 
> 
> Here's the page for integration for reference: https://github.com/sourcegraph/handbook/pull/4884/files#diff-7efe0e3a4e015b7d3b0c5913e62c457ef48bc4ce86bca1e04ce05a9d3de17551R11

By time commitment you mean the expected amount of time you'd see devoted to support during a week?  If it's that, I think it could be hard to quantify, I assume some weeks it'll be almost nothing and others quite busy.  What would you suggest?

**Comment by philipp-spiess** [comment]
> By time commitment you mean the expected amount of time you'd see devoted to support during a week? If it's that, I think it could be hard to quantify, I assume some weeks it'll be almost nothing and others quite busy. What would you suggest?

I was thinking of two things:

- Limiting the support to working hours only. I saw that you've added that already.
- Mentioning something about the actual time this will take during the working hours. I agree that we don't know that yet but maybe something like "try to set aside 30% of your time this week for eventual support tasks" could still be helpful. We could use this as a guideline when planing things so that it's clear that we won't have 100% availability during our support week.

**Review by taras-yemets — APPROVED** [review]
Great! Thank you, @scalabilitysolved!

**Review by valerybugakov — APPROVED** [review]

**Pull request merged**
