### PR TITLE
proposal: SOC2/GN-105 acceptance checklist

### LINKED ISSUE #29764: GN-105: Document process for deviating from standards
Add documentation to our [Continuous Integration](https://docs.sourcegraph.com/dev/background-information/continuous_integration) page that enumerates "break glass" scenarios (any time we have to deviate from a process) and our process for handling them.

Definition of Done: For any deviation from our process, we have a documentation for how it should be handled, and a running log of (an "audit trail") for these deviations.

### LINKED ISSUE #29894: GN-105: acceptance checklist
Similar to https://docs.gitlab.com/ee/development/code_review.html#acceptance-checklist , see 
RFC 566 https://docs.google.com/document/d/1d0o1O1ReazXKoDB_MANo1MuWfqBlgeU-5VZAAZRGamc/edit#heading=h.imubsmgidz8m

### PR DESCRIPTION
**Pull request by bobheadxi**
Introduces an acceptance checklist, to be applied to all pull requests, for the purposes of SOC2 compliance. The specific SOC2 control point we are hoping to tackle with this is:

> **GN-105**: Application and infrastructure changes are required to undergo functional, security, unit, integration, smoke, regression, and SAST testing prior to release to production.

Closes https://github.com/sourcegraph/sourcegraph/issues/29894 and closes https://github.com/sourcegraph/sourcegraph/issues/29764. The related tooling to help enforce this is being created in https://github.com/sourcegraph/sourcegraph/pull/30278

To learn more, see [RFC 568](https://docs.google.com/document/d/1d0o1O1ReazXKoDB_MANo1MuWfqBlgeU-5VZAAZRGamc/edit#heading=h.imubsmgidz8m)

### What will this mean?

All pull requests going through `sourcegraph/sourcegraph` will be greeted with a new pull request template that has a section with a checkbox with a link to the page introduced in this PR. Authors will be asked to either check said checkbox, or leave it unchecked with a brief explanation as to why the box remained unchecked.

A bot will come along once a PR has been merged and check for this checkbox. If left unchecked, an issue will be created in https://github.com/sourcegraph/sec-pr-audit-trail noting that an exception has been made. If no explanation is provided, the issue will remain open and the author will be tagged to document an exception and close the generated issue out manually.

image

### CODE REVIEW

**Review by jhchabran — APPROVED** [review]
🚀

**Comment by nicksnyder** [comment]
Do we honestly think this checkbox is going to be effective? I have a hard time believing this to be so. There was also no such checkbox and any previous company I have been at for code reviews (Google, LinkedIn).

This is literally the definition of "checking the box" type of useless control.

To satisfy this control, we just need to require that changes have tests. Can't we use codecov for this?

**Comment by keegancsmith** [comment]
I see we are basing it off GitLab's MergeRequest template, so I did the unscientific thing of looking at the last 9 closed merge requests to GitLab and 4 of those did not check the textbox. https://gitlab.com/gitlab-org/gitlab/-/merge_requests?scope=all&state=merged

Is there really no other way to meet this control? We have CI, a representative local devenv, code review, a release process and a culture of writing tests. I'm sympathetic that we want SOC2 compliance and the auditors may sticklers, but if I am not mistaken for each control you motivate why you meet that control. Is our tooling and culture not enough motivation? If not, how about adding into our template a "Test Plan:" that is required to not be empty. That was something [Facebook did](https://martinkonicek.medium.com/what-is-a-test-plan-8bfc840ec171) and I think would be way more effective than this.

Either way I'll share out an auto checkbox ticker extension :P

**Comment by jhchabran** [comment]
Thanks to both of you for jumping in 🙏!

@keegancsmith AFAIU, for each control we have to provide evidence that we meet the control, not just motivation on why this control is met. 

> Is our tooling and culture, not enough motivation? 

We initially assumed so too but after exchanging with the security team, they explained to us that the auditor is going to look for evidence and a set of principles is not enough. 

> those did not check the textbox

Yeah, the whole point in there is to be able to track exceptions, not checking something leads to an issue in the audit trail. 

>  Can't we use codecov for this? 

We can't use _just_ Codecov. We have to address every individual point of the control point AFAIU. 

> Do we honestly think this checkbox is going to be effective? 

I agree as much as you that ticking a checkbox is very much a "did you do your work? yes" thing. It provides a mechanism to track exceptions. It's just there to provide an initial process that we can iterate on as we go through. 

> There was also no such checkbox and any previous company I have been at for code reviews (Google, LinkedIn).

@nicksnyder, @keegancsmith can we move the discussion to the RFC? If you have any experience with dealing with SoC2 that would be incredibly valuable. 

Just to be clear there, our primary concern here is to get us through it in the tight schedule and gather feedback from the auditor so we can iterate into matching our culture accurately.

**Comment by coury-clark** [comment]
I also worked in a company that was SOC2 compliant, and we had no such checkbox. Having said that, I suspect many of the other aspects of the dev process (dedicated QA, lack of continuous delivery, etc) contributed to this "evidence".

I don't have any problem with this to achieve compliance quickly, but I do have a few observations / questions:
1. What do we plan to do with this backlog of "issues" of unchecked PRs? Many of them aren't going to have any actionable resolution.
2. The control specifically refers to release to prod, not merging to `main`. This feels like we might encounter some friction here since we may need to test things in an environment that only deploys from `main` - for example dogfood (this happens in Code Insights all the time). How do we plan to do something like this but still meet these criteria?

**Comment by jhchabran** [comment]
> What do we plan to do with this backlog of "issues" of unchecked PRs? Many of them aren't going to have any actionable resolution.

Just writing down that you tested things manually or that you had to merge on your because you're fixing an incident is enough. In that sense, that's merely a reminder to log an explanation and is actionable for the PR author. 

> The control specifically refers to release to prod, not merging to main. This feels like we might encounter some friction here since we may need to test things in an environment that only deploys from main - for example dogfood (this happens in Code Insights all the time). How do we plan to do something like this but still meet these criteria?

Aren't feature flags exactly covering that case? Because we're asserting compliance on the `main` branch, with enough flexibility, I don't see it getting in the way of merging a new feature that is only exposed in dogfood. 

> I also worked in a company that was SOC2 compliant, and we had no such checkbox. Having said that, I suspect many of the other aspects of the dev process (dedicated QA, lack of continuous delivery, etc) contributed to this "evidence".

To be frank, that's the crux of the problem here. If we are 100% failing a control point, we'd have only a little time to react, so buying us time to steadily iterate felt appropriate.

**Comment by coury-clark** [comment]
> Aren't feature flags exactly covering that case? Because we're asserting compliance on the `main` branch, with enough flexibility, I don't see it getting in the way of merging a new feature that is only exposed in dogfood.

I don't think we currently feature flag everything that would fall into this category. Maybe that's just something that needs to change, but in some cases we cannot test our features at the scale where they need to be tested until we get into the dogfood environment (or something similar that doesn't currently exist). I was more thinking that a lot of builds would end up unchecked simply because we don't have the ideal deployment flow for features such as Code Insights. I don't think this is a blocker for this, but just wanted to raise it and see if there were any thoughts (such as feature flagging more!).

**Comment by bobheadxi** [comment]
> Do we honestly think this checkbox is going to be effective? I have a hard time believing this to be so. [...] This is literally the definition of "checking the box" type of useless control.
>
> To satisfy this control, we just need to require that changes have tests. Can't we use codecov for this?

I think we briefly discussed code coverage as a requirement early on and dismissed it as also another "checking the box" requirement, but one that is actively obtrusive to workflows, requiring additional implementation where it is perhaps not relevant if we make it a hard requirement.

I think this checkbox may be effective in two ways:

- Simple, low-cost audit trail for SOC2 compliance
- Similar to how we reiterate company goals at company meetings, it is a light reminder that these recommended guidelines and principles exist with the _intention_ of helping everyone do their best work. It may be obvious (perhaps painfully so) to some, but I imagine as we grow it won't be feasible to expect the same level of familiarity/expertise with standards (for example, some of these acceptance points call out who to tag for certain types of changes that aren't easily denoted by CODENOTIFY etc), and even if folks only read this list once every dozen PRs I might be inclined to call it a bit of a win

> Either way I'll share out an auto checkbox ticker extension :P

I wouldn't strictly be against that, and actually this opens the door to what might be a decent idea: leaving the checklist item checked by default, removing the burden of proof from the author to indicate that they've done their due diligence, and allowing unchecking it to satisfy the SOC2 condition that we are tracking exceptions.

Either way, thank you all for chiming in here! JH's responses to the feedback here are aligned with my interpretation for the most part, and I hope that answers some of the questions/concerns 😄 However, the intent of this PR was to discuss the specific line items within the acceptance checklist - if the macro-level direction of these changes does not seem like the right path, we would greatly appreciate additional discussion within [RFC 568](https://docs.google.com/document/d/1d0o1O1ReazXKoDB_MANo1MuWfqBlgeU-5VZAAZRGamc), which has been tidied up and updated in response to this feedback.

**Comment by bobheadxi** [comment]
Copied from the [Slack discussion](https://sourcegraph.slack.com/archives/C07KZF47K/p1643906535369179?thread_ts=1643784224.091129&cid=C07KZF47K):

*Update* - we just confirmed with Security that `Test plan` is an acceptable solution from the SOC2 compliance POV, and the acceptance checklist will not be necessary in this scenario :smile: Since there seems to be pretty firm support around `Test plan`, the current plan going forwards is

* fold useful items from the checklist into the testing guide, and not introduce a distinct checklist
* proceed with a similar setup as proposed in https://github.com/sourcegraph/handbook/pull/2055 , but replacing the checklist with a free-form `Test plan` section that must have some content in it. We'll include a link to our testing guidance for the unfamiliar

Thank you all for the feedback and discussion! :pray:

**Pull request closed without merging**
