### PR TITLE
Use consistent terms for experimental and beta

### PR DESCRIPTION
**Pull request by malomarrec**

### CODE REVIEW

**Review by Joelkw — APPROVED** [review]
thanks!

**Review by quinnkeast — CHANGES_REQUESTED** [review]
I don't think this is actually accurate—we may need another way of putting this in the handbook.

Here, it's intended to clarify "early access enrollment" as the term in place of "onboarding customers" in what we're providing to Cloud customers right now. I'd describe the difference as "experimental describes the feature itself, early access enrollment describes the customer relationship with the feature + the action we're taking.

I'm not quite sure how to solve this... any thoughts?

**Comment by malomarrec** [comment]
@quinnkeast What do you think about the new proposal? (I assumed early access assumed "to a feature in beta or experimental", I don't see how we could do early access to something that is General Admission, that would be contradictory)

**Review by quinnkeast — APPROVED** [review]
Brilliant!

**Pull request merged**
