### PR TITLE
Add instructions for onboarding security audit logging for managed instances

### PR DESCRIPTION
**Pull request by ferozsalam**
Also fix indentation of bullet points in a couple of places

### CODE REVIEW

**Review by michaellzc — APPROVED** [review]

**Comment by michaellzc** [comment]
hey, I am fine with doing the manual step for now.

can this be automated somehow? Also I wonder what does the process look like on your end?

**Comment by ferozsalam** [comment]
Hey @michaellzc – you've been tagged in a Slack thread about this as well, but the process is [here](https://github.com/sourcegraph/infrastructure/pull/3477/files) – it involves changing some .tf, running `terraform apply`, adding a variable to a YAML array and then running `helm install`.

**Review by daxmc99 — APPROVED** [review]

**Comment by daxmc99** [comment]
Continued discussion occuring here: https://docs.google.com/document/d/1b3zw1j2vYTv5h0PXeu6s4bt3kw4TjYXRBCd6zPINaI8/edit#

**Comment by ferozsalam** [comment]
Superseded by https://github.com/sourcegraph/handbook/pull/3973

**Pull request closed without merging**
