### PR TITLE
docs(index.md): fix link

### PR DESCRIPTION
**Pull request by lloydchang**
See
https://github.com/sourcegraph/handbook/pull/6186#issuecomment-1455551328
https://github.com/sourcegraph/handbook/commit/9b527ba2369b3a6fd137d518a3f4dd0f45a5842b#r103192087

**Before:**

Screen Shot 2023-03-05 at 10 03 07 PM PDT

**Afterward:**

Screen Shot 2023-03-05 at 11 23 06 PM PDT

### CODE REVIEW

**Comment by lloydchang** [comment]
Hi @marekweb, @madisongclark
Cc @TrevorHoughton, @devoncoords

Please review this pull request https://github.com/sourcegraph/handbook/pull/6368 when your time permits.

Take care, and thank you!

**Comment by lloydchang** [comment]
Hi @marekweb, @madisongclark, @TrevorHoughton, @devoncoords,

I don't see a "Reopen" button as github-actions bot recommends because I am not a maintainer of this handbook repository.

When your time permits:

• Would you route it to the right team, reopen this, and consider merging it?

It is a 1-line change.

Thank you!

**Comment by lloydchang** [comment]
@vdavid Can you help me with this https://github.com/sourcegraph/handbook/pull/6368?  Thank you.

**Comment by vdavid** [comment]
Thanks for your suggestion, @lloydchang, it sheds light on a very important visibility issue!

@amieroth and @marekweb, what do you think about this change?

The current [doc link](https://docs.google.com/document/d/1WqyffCTaPKp9G1kpPFryEi2eiPZzwfF7Gmo2mAjSq40/edit#heading=h.kso9gsaecr0b) is better _internally_ because it contains 11 issues of The Git Down, while the [external link](https://us8.campaign-archive.com/home/?u=df2a46502c53acf0b7771317f&id=e8e7daeb55) only contains three. But the doc is not available externally.

Ideas to solve this:
a.) Merge this PR without more changes – but then we'll lose internal visibility of 8 of the issues
b.) Share the doc publicly and close this PR
c.) Add the rest of the issues to the mailchimp campaign archive link (I don't think it's possible tbh), and then merge this PR

Thoughts?

**Comment by lloydchang** [comment]
@vdavid

An idea:
d.) Two links: 1. Internal and 2. External.

I can amend this pull request to try that.

For example:
> [The Git Down](https://docs.google.com/document/d/1WqyffCTaPKp9G1kpPFryEi2eiPZzwfF7Gmo2mAjSq40/edit#heading=h.kso9gsaecr0b)
> [(external link)](https://us8.campaign-archive.com/home/?u=df2a46502c53acf0b7771317f&id=e8e7daeb55)

**Comment by vdavid** [comment]
@lloydchang that'd work! Huge thanks if you update the PR with that! The design for that is not straightforward.

**Comment by lloydchang** [comment]
**Afterward:**
> [The Git Down](https://docs.google.com/document/d/1WqyffCTaPKp9G1kpPFryEi2eiPZzwfF7Gmo2mAjSq40/edit#heading=h.kso9gsaecr0b)
> [(external link)](https://us8.campaign-archive.com/home/?u=df2a46502c53acf0b7771317f&id=e8e7daeb55)
> 
Screen Shot 2023-04-08 at 7 38 42 AM

**Comment by lloydchang** [comment]
@vdavid Please review when your time permits. Thank you!

**Comment by lloydchang** [comment]
Close https://github.com/sourcegraph/handbook/pull/6368 because of https://github.com/sourcegraph/handbook/pull/6715 by @madisongclark
> Update Git Down block #6715
[madisongclark](https://github.com/madisongclark) commented [12 hours ago](https://github.com/sourcegraph/handbook/pull/6715#issue-1666731423)
I frequently receive requests from external (non-Sourcegraph) people to view the Git Down. This is intended to be an internal-only doc since it includes sensitive info about ARR and teammate accomplishments (including anniversaries and birthdays). I've added "Internal only" to the block name to hopefully make this more clear.

**Pull request closed without merging**
