### PR TITLE
dotcom: update site config change instructions

### PR DESCRIPTION
**Pull request by sanderginn**
Nothing about this page was factual anymore 🙃

### CODE REVIEW

**Comment by sanderginn** [comment]
Current dependencies on/for this PR:
* main
  * **PR #6623** <a href="https://app.graphite.dev/github/pr/sourcegraph/handbook/6623" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/sourcegraph/handbook/6623?utm_source=stack-comment).

**Review by burmudar — APPROVED** [review]
I think the numbering is borked but think that is a known issue ... besides it was borked before too 🤷🏼

**Comment by sanderginn** [comment]
naah it's [legal Markdown syntax](https://www.markdownguide.org/basic-syntax/#ordered-lists). I always thought this was done to prevent having to manually keep the numbers aligned when inserting an item in the middle of a sequenced list.. but now I see that none of that matters as long as the list starts with a 1 🦐

**Comment by pjlast** [comment]
Thanks!

**Pull request merged**
