### PR TITLE
engineer: Add how to be a tech lead

### PR DESCRIPTION
**Pull request by indradhanush**
I just converted this to markdown. Others who wrote this are tagged as co-authors. Apologies if I missed anyone.

Original doc is here: https://docs.google.com/document/d/15vfYnWpBgBNTuFzUHOiOwzmGjVtLGLgyAXjbsZILqEQ/edit#

### CODE REVIEW

**Review by kalanchan — APPROVED** [review]
looks good! thanks for doing this

**Review by varsanojidan — APPROVED** [review]
Great idea!

**Review by sashaostrikov — APPROVED** [review]
LGTM! You just need to fix some absolute handbook links

**Comment by mrnugget** [comment]
Thanks @indradhanush! Ship it. Can you post in #job-fair too that this is moved?

**Pull request merged**
